"""Tests for lossless/idempotent metering: reproducible window reads, durable
state, and stable batch identity."""

import json
from pathlib import Path

from wisp_agent.metering_state import (
    MeteringState,
    PendingBatch,
    load_state,
    new_batch_id,
    save_state,
)
from wisp_agent.stats_adapter import read_log_stats
from wisp_agent.telemetry import UsageBatch, serialize


def _line(model: str, original: int, optimized: int, output: int = 1) -> str:
    return json.dumps(
        {
            "model": model,
            "input_tokens_original": original,
            "input_tokens_optimized": optimized,
            "output_tokens": output,
        }
    )


def test_end_bound_reproduces_identical_window(tmp_path: Path):
    """Re-reading [0, end) is byte-identical even after more lines append — this
    is what makes a retried batch idempotent."""
    log = tmp_path / "run.jsonl"
    log.write_text(_line("m", 100, 40) + "\n" + _line("m", 200, 80) + "\n")

    stats2, end2 = read_log_stats(log, offset=0)
    assert stats2[0].input_tokens_original == 300  # 100 + 200

    # A new line appended after the window must NOT change the replayed window.
    with log.open("a") as fh:
        fh.write(_line("m", 999, 1) + "\n")

    replay, replay_end = read_log_stats(log, offset=0, end=end2)
    assert replay_end == end2
    assert replay[0].input_tokens_original == 300  # third line excluded

    # And the delta after the committed offset is exactly the new line.
    delta, _ = read_log_stats(log, offset=end2)
    assert delta[0].input_tokens_original == 999


def test_state_roundtrip(tmp_path: Path):
    p = tmp_path / "state.json"
    st = MeteringState(
        committed_offset=128,
        window_start="2026-06-15T00:00:00+00:00",
        pending=PendingBatch(batch_id="b1", window_start="s", window_end="e", to_offset=256),
    )
    save_state(p, st)
    assert load_state(p) == st


def test_load_missing_returns_fresh(tmp_path: Path):
    st = load_state(tmp_path / "nope.json")
    assert st == MeteringState()
    assert st.committed_offset == 0 and st.pending is None


def test_load_corrupt_returns_fresh(tmp_path: Path):
    p = tmp_path / "state.json"
    p.write_text("{ not valid json")
    assert load_state(p) == MeteringState()


def test_save_creates_parent_dirs(tmp_path: Path):
    p = tmp_path / "sub" / "dir" / "state.json"
    save_state(p, MeteringState(committed_offset=7))
    assert load_state(p).committed_offset == 7


def test_new_batch_id_is_unique():
    assert new_batch_id() != new_batch_id()


def test_batch_id_autogenerated_and_serialized():
    b = UsageBatch(
        tenant_id="t",
        device_id="d",
        agent_version="0.1.0",
        headroom_version="0.25.0",
        window_start="s",
        window_end="e",
        events=[],
    )
    assert b.batch_id  # auto-generated uuid
    assert serialize(b)["batch_id"] == b.batch_id


def test_batch_id_explicit_is_preserved():
    b = UsageBatch(
        tenant_id="t",
        device_id="d",
        agent_version="0.1.0",
        headroom_version="0.25.0",
        window_start="s",
        window_end="e",
        events=[],
        batch_id="fixed-1",
    )
    assert serialize(b)["batch_id"] == "fixed-1"
